#!/bin/bash
echo "Building $1 program";
make clean
make
rc=$?

if [ $rc -eq 0 ]; then
	echo "Return code=$rc" >> return_code.txt
	echo "Build successful";
	./hello_world
	exit 0;
else
	echo "Return code=$rc" >> return_code.txt
	echo "Build failure";
	exit 1;
fi

